### PR TITLE
Change package name so that it not collides with popular erlang package

### PR DESCRIPTION
**Pull request by jfrolich**
`uuid` is a package that is used a lot in the erlang ecosystem. And if any package has that as a dependency and also uses this the dependencies will collide and it will not work.

There are two ways forward: the erlang `uuid` package changes it's app name, or this package changes the app name. 

Because the erlang package is around much longer and is more popular I would suggest to change this name. I would suggest publishing a new package under the `elixir_uuid` name, and deprecate the uuid named package asking people to upgrade. This will keep all current apps working, and we can fix packages that depend on uuid by updating the dependency to `elixir_uuid`.

### CODE REVIEW

**Comment by jfrolich** [comment]
For people that have the same problem, you can use my fork of `uuid` as a github source in your mixfile. If the author of this package will fix it I will try to convince other package that depend on `uuid` to upgrade as well. In my case it was `exq` and `ex_sentry`.

**Comment by rbino** [comment]
I have the same problem trying to use CQEx and Guardian in a project (CQEx uses cqerl that in turn uses `uuid_erl`, while Guardian uses this package).
@zyro are you considering the package name change or have you found another way around this issue?

**Comment by zyro** [comment]
Apologies I've not had much time to spend on this but I'm open to solutions. This is an odd problem but I'm happy to rename the application. Possibly a `2.0.0` is more appropriate than `1.2.0` though?

It would however leave the [uuid_erl package](https://hex.pm/packages/uuid_erl) with the `:uuid` app name and the [uuid package](https://hex.pm/packages/uuid_erl) with the `:elixir_uuid` app name, which feels funky - thoughts?

Ideally there would be a way to alias applications like other platforms can alias conflicting imports, but I recognise that's significantly more work. I do like that with this approach there would be no breaking changes for the dependents though, and they could update to the new version at their own pace. 👍

**Comment by jfrolich** [comment]
I agree it's not ideal, it would be better for hex to enforce unique naming of apps.

> It would however leave the uuid_erl package with the :uuid app name and the uuid package with the :elixir_uuid app name, which feels funky - thoughts?

Yeah thats a bit funky. The app name is mainly transparent for the user, so it shouldn't be a large problem.

**Comment by zyro** [comment]
You're right, given it's ultimately transparent for the user `1.2.0` should be appropriate. Thanks!

**Pull request merged**
