### PR TITLE
Added the ability to render UUIDs as a :slug, A slug is a URL safe Ba…

### PR DESCRIPTION
**Pull request by kraythen**
I have been working on an application that uses the elixir-uuid library and I have written my own code to handle slug conversion. I thought I would put it in this library as another format that the user could get a UUID in and thus make use of it. 

Added the ability to render UUIDs as a :slug, A slug is a URL safe Base 64 encoded UUID with the padded == stripped which can be used on a URL.

### CODE REVIEW

**Comment by kraythen** [comment]
Is this repository being maintained anymore?

**Comment by zyro** [comment]
@kraythen It is, but I have very limited time to spend on it - I'll go through this PR as soon as I can. Until then looks like Travis is complaining, any ideas why?

**Comment by kraythen** [comment]
Any chance of getting this merged?

**Comment by zyro** [comment]
As soon as I can find a spare moment to figure out the CI failure this PR introduces.

**Comment by kraythen** [comment]
Greetings, any chance of this getting added ?

**Comment by zyro** [comment]
@kraythen Yes I'm still maintaining this as best I can, but I haven't had time to look into the CI failure yet.

**Comment by kraythen** [comment]
the CI build is running on 1.3.4 and failing tests.

**Comment by kraythen** [comment]
I have fixed the CI problems. The Elixir version and OTP version were the problem. Can we get a merge and publish?

**Comment by zyro** [comment]
Nothing I can see from the changes would require a version bump straight to Elixir 1.7. What am I missing?

**Comment by kraythen** [comment]
I dont know why but before this build the code had "codepoint" invalid character failures on characters that werent even there. Bumping the elixir version fixed it. Question would be is if there is any reason to NOT bump the elixir version. If so then we have to find the right version above 1.3 where it works but not too high.

**Comment by zyro** [comment]
Ideally I want to target the lowest version possible to ensure this is as widely usable as possible. I'll merge as is and experiment with lower versions at some point before I tag a new version.

**Comment by zyro** [comment]
@kraythen Thanks!

**Pull request merged**
