### PR TITLE
uuid4: use stronger random byte generator function

### PR DESCRIPTION
**Pull request by sunaku**

### CODE REVIEW

**Comment by zyro** [comment]
`:crypto.strong_rand_bytes/1` may throw `:low_entropy` exception. What's your take on handling that, or its likelihood?

**Comment by sunaku** [comment]
Good point. :+1:  Updated patch is force-pushed now:

>    This patch makes `UUID.uuid4()` try `:crypto.strong_rand_bytes()` first
    and if that fails, due to the system not having enough entropy, then it
    falls back to the prior method of using `:crypto.rand_bytes()` instead.

**Comment by zyro** [comment]
Hmm, my understanding is if `:low_entropy` is thrown, it will keep happening until the random source is re-seeded. Catching it will hide the problem indefinitely.

What do you think about adding an optional parameter (something like `strong_random: true/false`) which toggles between `:crypto.rand_bytes/1` and `:crypto.strong_rand_bytes/1`? This ensures the caller is allowed to handle `:low_entropy`, and if we default this to `false` we can preserve the current default behaviour.

**Comment by sunaku** [comment]
Sure, that would work. :+1:

**Comment by eproxus** [comment]
Just my 2 cents: I think strong random should be the default, and it should throw an exception in case of low entropy. This is not something you want to hide. An option to change to weak random bytes or fallback to weak random bytes would be appropriate.

As for the chance of it happening, I've never seen it in production, so I would assume it is a very rare case (just an anecdote, I know).

**Comment by sunaku** [comment]
@eproxus I have restored my original patch 3e2dda302f3d8dad42e2d983de19943881270655 (which does exactly what you're asking for) into this PR.  In addition, @zyro's suggestion is still available in the secondary patch 84ddee8fdf8bd1e6d905db2d8c717bde4d86fd9d. It's your decision! :speak_no_evil:

**Comment by eproxus** [comment]
Well, 3e2dda3 is preferable. The least amount of surprises. :smile:

**Comment by zyro** [comment]
I like the more explicit https://github.com/zyro/elixir-uuid/commit/3e2dda302f3d8dad42e2d983de19943881270655 over the alternative. If you switch back to that I'll auto-merge it. Otherwise I'll pick out that commit and manually merge it later.

That said, I did find [this](https://github.com/erlang/otp/blob/maint/lib/crypto/src/crypto.erl#L643) used in a couple of places, so it looks like the automatic fallback isn't entirely bad. Something to think about I suppose.

**Pull request closed without merging**
